version: '3.8'

services:
  eliza:
    build:
      context: .
      dockerfile: docker/Dockerfile.prod
    container_name: eliza
    restart: always
    volumes:
      - ./data:/app/data
      - ./characters:/app/characters
      - ./.env:/app/.env
      - ./logs:/app/logs
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - TZ=UTC
    healthcheck:
      test: ["CMD", "node", "docker/healthcheck.js"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - eliza_network

networks:
  eliza_network:
    driver: bridge

volumes:
  data:
  characters:
  logs: